### ISSUE TITLE
Enhance results accordion to indicate that the title bars are tappable

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/election-results#14]
One needs to hover a cursor over a results title to realize that it's clickable; on a tablet, there's no indication that the list is anything but a list of job titles.

Possible implementation using WAB styling:
![image](https://cloud.githubusercontent.com/assets/2125181/12363580/5eb6335a-bb7e-11e5-88a1-7da4ac31bebd.png)

**Comment by LindsayThomas** [comment]
Added to correct repo as enhancement. 

This is the older repo for the JS app
