### ISSUE TITLE
Enhance results to hide races irrelevant to searched location

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/election-results#15]
In the results below, the Senate 24th and 42nd districts don't apply because the searched location is in the 48th district.  Better to just hide the irrelevant races.
![image](https://cloud.githubusercontent.com/assets/2125181/12363641/c49c3cb4-bb7e-11e5-8143-2bc01842c88e.png)

**Comment by LindsayThomas** [comment]
The grayed out design is a feature. It visualizes all configured layers because there isn't another way to illustrate all the available chart info.

This is the incorrect repo for the related table charts widget.
